# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
