# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_application', '0005_medicalhistorycategorydetailkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
