# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd_application', '0008_auto_20160325_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalexamdetail',
            old_name='value',
            new_name='real_value',
        ),
        migrations.AddField(
            model_name='physicalexamdetail',
            name='str_value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
